### ISSUE TITLE
set_property could not find TARGET benchmark::benchmark

### ISSUE THREAD

**Issue by Akshay-9416** [google/benchmark#1074]
Hi everyone, I am trying to 
$colcon build
performance_test_fixtures from repo link below
https://github.com/ros2/performance_test_fixture
at corresponding CMakeLists.txt file line 46  target_link_libraries(benchmark::benchmark ........)
was producing an error so I made a work around by adding the below lines and omiting benchmark::benchmark  

install(
  EXPORT benchmarkTargets
  FILE benchmarkTargets.cmake
  NAMESPACE is::
  DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/benchmark
)
include(CMakeFindDependencyMacro)
find_dependency(benchmark)
include("${CMAKE_CURRENT_LIST_DIR}/benchmark/build/src/CMakeFiles/Export/lib/cmake/benchmark/benchmarkTargets.cmake")

I have also put the benchmark folder from this repo inside performance_test_fixture and followed the instructions provided here
https://github.com/google/benchmark
now I am getting a new error when I am running 
$colcon build
![image](https://user-images.githubusercontent.com/60077708/101175065-b53c6700-366a-11eb-9721-d2f764733eaf.png)

can anyone please point out what's the issue in my approach and suggest better approach.

**Comment by dominichamon** [comment]
It seems that the find_package didn't find benchmark, but i would have expected that to fail out earlier. I don't know anything about colcon so i can't comment on those specifics.

If you instead have the benchmark folder in the repo and are using "add_subdirectory" then it should also just work. I imagine this might be some odd relationship between colcon and cmake?

Is it also possible you have an older benchmark version (in which the library was just 'benchmark' rather than 'benchmark::benchmark'?
