### ISSUE TITLE
deprecate KeepRunning loop

### ISSUE THREAD

**Issue by dominichamon** [google/benchmark#110]
depends on #109 

Once we have test fixtures, we can pull the KeepRunning loop into the framework and remove the boilerplate. We'll still pass in the State and have it mutable but it will be unused in many simple cases.

**Comment by dominichamon** [comment]
This might end up putting overhead on the benchmark (due to the extra function call per iteration). To be tested.

**Comment by EricWF** [comment]
@dominichamon I really don't think we should depreciate the "KeepRunning()" loop.

Remembering that the timer only runs over the the contents of the loop, and not anything that comes before or after it. So Fixtures don't really buy us anything in terms of setup/teardown.

Don't you think that setting up a fixture has more boilerplate than simply using the "state" object?

**Comment by dominichamon** [comment]
i do think that fixtures have more boilerplate, however i also think that it's expected boilerplate. the 'timer doesn't run outside the loop' is a tricky concept for people to get out of the box.

having two ways of doing setup/teardown makes me sad.

**Comment by EricWF** [comment]
I need to update the doc to make that point explicit. However I don't think we should deprecate the KeepRunning() loop. I actually prefer that interface to the fixture one and I think others do as well.

Also one nice thing about using "KeepRunning()" inside the benchmark instead of repeatedly calling the benchmark function as suggested is that we can force the compiler to inline "KeepRunning()" because we own the function. However we can't force the compiler to inline repeated calls into a users benchmark function. (Am I making sense?)

**Comment by dominichamon** [comment]
yes of course, that's why i have the comment above about the extra function call per iteration.

maybe we just need clear documentation around when to use a fixture and when to use the space around the loop. ie, state.

**Comment by EricWF** [comment]
For sure. Should we close this issue though or do you still want to consider deprecating that interface.
