### ISSUE TITLE
[FR] Migrate real-time disscussions

### ISSUE THREAD

**Issue by LebedevRI** [google/benchmark#1317]
Currently, #benchmark @ libera IRC channel is suggested.
From practice, the channel is dead.

As it happens, for some time now i've been experiencing halide's approach to this problem, https://gitter.im/halide/Halide.
While it does seem like a bad change to go from IRC to something else,
it's surprisingly not a problem at all, and works almost seamlessly: https://irc.gitter.im/

Perhaps it may be a good change?

**Comment by dominichamon** [comment]
i haven't found a great solution to real-time at all... do you think irc is dead because there's no project owners online (i'm out of the habit of connecting) or because it's just not useful for this project?  iirc, slack was pretty much dead when i was trying that too.

i'm open to anything that you, others, the community around this project feels would work.

**Comment by LebedevRI** [comment]
I think that *channel* is dead, for whatever reasons (the project is somewhat special),
I don't know that "moving" it to gitter will help, but i don't think it will make things any worse.

**Comment by LebedevRI** [comment]
If this isn't going to happen please just close the issue, thanks.

**Comment by LebedevRI** [comment]
Ok, nowadays i think we actually should just mention that the channel is also avaliable from Matrix.

**Comment by dmah42** [comment]
alongside IRC we now have discord (https://discord.gg/cz7UX7wKC2).  i haven't been able to get a gitter set up because Google.

**Comment by LebedevRI** [comment]
Yay, more fragmentation!

**Comment by dmah42** [comment]
![image](https://github.com/google/benchmark/assets/510002/a71b882d-c3a8-4fef-adad-3f88b90e6240)
