### ISSUE TITLE
[BUG] Iterations(...) not honored in case a CLI option is given

### ISSUE THREAD

**Issue by ton** [google/benchmark#1471]
I am using the following to hard-code the number of iterations for a specific benchmark:

```
BENCHMARK(...)->Iterations(...);
```

This works, until I specify some command-line option, for example a filter on the benchmarks to run. As soon as some `--benchmark` CLI option is specified, the hard-coded iterations number is ignored and behavior is the same as if no iterations were specified in the code. I would expect the hard-coded number of iterations to be honored in all cases.

On the subject of influencing the number iterations; it would also be nice to be able to specify the number of iterations on the command-line instead of having to modify the code for this. My use case is that I want to run the code for a specific benchmark only once, to measure the number of instructions executed using `perf stat`. 

System: Linux, GCC 12.1

**Comment by dominichamon** [comment]
> I am using the following to hard-code the number of iterations for a specific benchmark:
> 
> ```
> BENCHMARK(...)->Iterations(...);
> ```
> 
> This works, until I specify some command-line option, for example a filter on the benchmarks to run. As soon as some `--benchmark` CLI option is specified, the hard-coded iterations number is ignored and behavior is the same as if no iterations were specified in the code. I would expect the hard-coded number of iterations to be honored in all cases.

agree that this sounds like a bug and not intended. it _is_ intended that command line options should override code configuration, but only per-option.

do you still get an `/iterations` suffix on the benchmark name?

> 
> On the subject of influencing the number iterations; it would also be nice to be able to specify the number of iterations on the command-line instead of having to modify the code for this. My use case is that I want to run the code for a specific benchmark only once, to measure the number of instructions executed using `perf stat`.

we used to have this. it doesn't interact well with the way that we determine how long to run benchmarks for.  this is because we calculate the number of iterations from the min time and some notion of "significance": https://github.com/google/benchmark/blob/main/docs/user_guide.md#runtime-and-reporting-considerations

when we had an iterations override on the command line alongside the minimum time setting, it was possible to get into all sorts of trouble with unexpected results.

looking at how the code has changed though, i think we could introduce it again. 

> 
> System: Linux, GCC 12.1

**Comment by ton** [comment]
I will try to come up with some minimal example that reproduces the issue. I tried to create one but that did not show the issue, so I have to revisit the code where the issue occurred, and drill down to the root cause. There is more going on here than I initially suspected.

**Comment by ton** [comment]
I can no longer reproduce the problem I saw; probably some mistake I made on my part, sorry for the noise.
