### ISSUE TITLE
Additional statitistics and complexity should be calculated outside of the reporter.

### ISSUE THREAD

**Issue by EricWF** [google/benchmark#225]
Most of the replicated code in the reporters is dedicated to computing additional statistics and complexity reports. I believe this would be better done outside of the reporters. I'm currently working on such a change.

However I wanted to confirm with @ismaelJimenez that such a change would be appropriate for his needs. Do you have a custom reporter that needs all of the complexity reports or would it just be sufficient for `ReportComplexity` to simply be given the two precomputed complexity reports?

**Comment by EricWF** [comment]
@ismaelJimenez I would also like to consider removing the "ReportComplexty" interface all together. Instead the complexity reports would be precomputed and passed to "ReportRuns" as appropriate. Do you think this would work for your case?

**Comment by ismaelJimenez** [comment]
@EricWF Yes, I think the solution you propose should work. The reason why I implemented it like that was to keep consistent with the current implementation of "ComputeStats" that was already in place, and I took it as a guideline. As ComputeStats is done inside the reporter I also did the same with "ComputeBigO". I would suggest that any refactoring of the code done to BigO calculations is done also to ComputeStats in the same way because I think they are quite similar from the logical point of view (both give a summary report).

I also thought about doing the complexity report inside "ReportRuns", but finaly I decided for a separate function because "ReportComplexity" shall only be done at the end of a family of benchmarks and "ReportRuns" is called at the end of each benchmark. I didn't want add the logic of complexity reporting into "ReportRuns" and kept it as separate function in order to not mess too much with existing code. 

You said that you are already working on the changes, so I propose that once you have the changes I can have a look at them and check whether everything works OK. Also if I can help you with the changes please just let me know. 

Thanks

**Comment by EricWF** [comment]
Sounds good! I think your initial implementation made the most sense given the current interface.

Pull Request #226 is the changes I'm suggesting.

**Comment by EricWF** [comment]
This has been fixed.
