### ISSUE TITLE
benchmark hangs with non-integral RangeMultiplier

### ISSUE THREAD

**Issue by NAThompson** [google/benchmark#244]
The following code hangs google/benchmark:

    BENCHMARK(BM_FibRecursive)->RangeMultiplier(1.6)->Range(1, 1<<5);

There is no compiler warning, nor build error, simply a hang at runtime.

**Comment by ismaelJimenez** [comment]
I just launched a pull request that shall fix the hang you are experiencing. The problem you are having is not related to non-integral, as the interface to RangeMultiplier only accepts integers. So, your call to range multiplier with parameter 1.6 is morally equivalent to call it with parameter 1. And the problem was that we did not have a check for this extreme case, that represents an invalid input. With the check I added your call shall fail but not hang.

**Comment by EricWF** [comment]
Closing since this has been fixed already.
