### ISSUE TITLE
Calculating Deviation

### ISSUE THREAD

**Issue by massey101** [google/benchmark#255]
Hi,
I'm thinking of adding a min/max to the calculations. This is useful to me as we have a project with a maximum latency requirement. Other measurements like standard deviation could also be included.

Would this sort of thing be acceptable?

**Comment by dominichamon** [comment]
If you specify 'repetitions' we will calculate the mean and std dev across each repetition. Ie, we take the average per-iteration time, and then find the mean/std dev of those averages.

it sounds like you're suggesting we should have the std dev, max, and min, of the iterations over a single run. i think that's a great idea, and with the more flexible reporters it should be something that can be easily included (the tabular reporter has limitations due to laying out columns).

**Comment by LebedevRI** [comment]
>If you specify 'repetitions' we will calculate the mean and std dev across each repetition. Ie, we take the average per-iteration time, and then find the mean/std dev of those averages.

For **this** use-case, my pr will fix the issue.

> it sounds like you're suggesting we should have the std dev, max, and min, of the iterations over a single run.

But not for this one...
I too think it may be nice to have, but wouldn't it be a little bit memory-prohibitive to keep all the measurements for each iteration? There can be a lot of iterations, and we'd need 8 bytes (`sizeof(double)`) for each one...
