### ISSUE TITLE
Warn when running under non-fixed CPU frequency

### ISSUE THREAD

**Issue by baryluk** [google/benchmark#325]
I.e. on Linux warn (with a URL to explanation how to fix it / bypass, or a command line with sudo to explain how to fix it quickly manually), when something else than 'performance' cpu frequency governor is used or not all CPUs are set to the same frequency,

If running under root, maybe automatically set it to fixed and max frequency and when exiting benchmark return back to previous state (with proper diagnostic to the stderr maybe).

It is very common to set this manually, but I think it is good idea to put it in the framework, as not everybody know about such things.

**Comment by EricWF** [comment]
I agree we should try and emit some sort of warning; We used to but I removed it while re-writing the timing internals.

> when something else than 'performance' cpu frequency governor is used or not all CPUs are set to the same frequency,

Unfortunately checking for the 'performance' CPU governor isn't a great way to detect CPU scaling. Depending on the loaded CPU  module/driver the scaling govenor may be ignored (e.g. [Intel P-state](https://wiki.archlinux.org/index.php/CPU_frequency_scaling)).

However checking that all of the CPU's share the same frequency should be a fairly good test to detect scaling.

However I don't think the library should mess with the system's CPU governor. It requires root privileges and we shouldn't encourage running benchmarks as root. Also I don't think we shouldn't be messing with system wide settings that affect other programs. Additionally we can't know the correct max frequency to set the CPU to, since the max frequency reported by the CPU may actually be it's max turbo speed and not max clock speed w/o turbo.

Patches welcome :-) I would suggest changing the `Initialize` function in `benchmark.cc` to detect and report CPU scaling.

**Comment by ensonic** [comment]
I've tried to run my benchmark as below:
```
sudo cpufreq-set -g performance
./my-bench
sudo cpufreq-set -g powersave
```
but still get the warning. Any idea?

Ideally we had a benchmark runner that could change the freq-scaling, but I could not find any.

**Comment by dominichamon** [comment]
using cpupower works for me:

```
$ sudo cpupower frequency-set --governor performance
...
$ test/basic_test 
Run on (12 X 3900 MHz CPU s)
2017-10-30 16:20:52
***WARNING*** Library was built as DEBUG. Timings may be affected.
--------------------------------------------------------------------------------------
Benchmark                                               Time           CPU Iterations
--------------------------------------------------------------------------------------
...
$ sudo cpupower frequency-set --governor powersave
...
$ test/basic_test 
Run on (12 X 3900 MHz CPU s)
2017-10-30 16:21:02
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
***WARNING*** Library was built as DEBUG. Timings may be affected.
--------------------------------------------------------------------------------------
```

If this is common (and not some quirk of my set up) then maybe that's what should be linked either in the README or the warning.

**Comment by ensonic** [comment]
@dominichamon thanks, yours works, so +1 for adding this to the docs.

**Comment by dominichamon** [comment]
so we warn, and we have documentation. closing this.
