### ISSUE TITLE
use std::chrono::steady_clock instead of walltime

### ISSUE THREAD

**Issue by predmond** [google/benchmark#35]
It looks like walltime can be simplified/replaced and made portable by using std::chrono::steady_clock

**Comment by EricWF** [comment]
A couple of issues with this:

- Walltime seems to be a much faster implementation than std::chrono::steady_clock (or high_resolution_clock). Ironically I haven't benchmarked this quite yet.

- We don't know if the standard library implementation is going to have support for std::chrono yet because we support c++0x along with c++11.


We could use it as a fallback implementation if we can't use the non-portable walltime implementation

**Comment by dominichamon** [comment]
Fixed in #104
