### ISSUE TITLE
Use of non const reference parameter violates google coding style

### ISSUE THREAD

**Issue by schoetbi** [google/benchmark#394]
It is required that the state is passed by non const reference to the test function. This violates the google styleguide rule [`runtime/references` ](https://google.github.io/styleguide/cppguide.html#Reference_Arguments)

```
static void BM_StringCreation(benchmark::State& state) {
  while (state.KeepRunning())
    std::string empty_string;
}
// Register the function as a benchmark
BENCHMARK(BM_StringCreation);
```

What are the arguments?

**Comment by dominichamon** [comment]
there's no good argument for it. it was developed within google as an alternative API to the existing benchmark solution (that couldn't be open sourced due to tangled dependencies) and this was marginally cleaner to implement than passing pointers around.

I'd be comfortable changing to `benchmark::State*` to be compliant but that is a breaking API change that needs to be handled carefully.

**Comment by EricWF** [comment]
I'm not sure there is a good enough reason to break the existing API and make the change.

IIRC the main rational against passing input parameters as non-const references is that it's confusing to the callers of that function; That is it's unclear at the callsite if the argument will be mutated.

However the only call sites for registered benchmarks are *inside* the library itself, and internally there is certainly no confusion about what happens to the `State` argument.

Additionally I don't see any API issues or confusion arising for the callee.

Since the current API, although inconsistent with the style guide, isn't confusing or detrimental to users, and since it would be a pain to change, I don't see why we would.

Note: It would be possible, with a little work, to support both API's to avoid breaking backwards compat. However I don't think it's worth the trouble.

**Comment by schoetbi** [comment]
The problem for me arose because I used the cpplint.py script to check my complete codebase and got errors for every benchmark I wrote.
I do not suggest to change anything in the API.
That it is not worth the trouble. Honestly I would rather change the rule of not using non-const references as parameters in the coding guideline. The reason for this is that a reference has the property of never being null. That alone makes it superior to pointers. 
I saw a posibility in the cpplint.py script to disable this rule. That solves the issue for me. Thanks.
