### ISSUE TITLE
Latest tag is not annotated

### ISSUE THREAD

**Issue by verbit** [google/benchmark#411]
My Git client does not recognize the `v1.1.0` tag as annotated.
```
$ git --version
git version 2.11.0 (Apple Git-81)
$ git clone https://github.com/google/benchmark && cd benchmark
$ git checkout tags/v1.1.0
$ git describe
v0.1.0-461-g710c2b8
$ git describe --tags
v1.1.0
```
The following also suggests that `v1.1.0` is not tagged.
```
$ git show-ref -d --tags
a5c8da0c9a598cdfb3fc58aa15e88bd966b671eb refs/tags/v0.0.9
8b0b73f06c615f2712e69e0d4ea1a356b8b7a445 refs/tags/v0.0.9^{}
73b734eb1fe857296e49528cd2413640aab7c40e refs/tags/v0.1.0
006d23ccca1375a973b7fae0cc351cedb41b812a refs/tags/v0.1.0^{}
cd525ae85d4a46ecb2e3bdbdd1df101e48c5195e refs/tags/v1.0.0
4f8bfeae470950ef005327973f15b0044eceaceb refs/tags/v1.1.0
```

As a result, CMake build reports the wrong version (since `GetGitVersion` only considers annotated tags). Can someone check if he can reproduce it or tell me if I am doing something wrong?

P.S.
Regarding the advent of `benchmarkConfigVersion.cmake` it might be reasonable to drop the `v` version prefix from `GetGitVersion`'s result (especially, so that [COMPATIBILITY SameMajorVersion](https://github.com/google/benchmark/blob/master/src/CMakeLists.txt#L52) works). But this is probably another issue.

**Comment by dominichamon** [comment]
are you sure you're on the latest? have you pulled tags?

$ git show-ref -d --tags
a5c8da0c9a598cdfb3fc58aa15e88bd966b671eb refs/tags/v0.0.9
8b0b73f06c615f2712e69e0d4ea1a356b8b7a445 refs/tags/v0.0.9^{}
73b734eb1fe857296e49528cd2413640aab7c40e refs/tags/v0.1.0
006d23ccca1375a973b7fae0cc351cedb41b812a refs/tags/v0.1.0^{}
cd525ae85d4a46ecb2e3bdbdd1df101e48c5195e refs/tags/v1.0.0
d76e2e66e0c3d46817227291dd7513c5db8f8b87 refs/tags/v1.1.0
4f8bfeae470950ef005327973f15b0044eceaceb refs/tags/v1.1.0^{}


$ git describe
v1.1.0-112-g9d4b719

$ git describe --tags
v1.1.0-112-g9d4b719


Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by verbit** [comment]
> are you sure you're on the latest?
```
$ git log
commit 9d4b719daeda35acf3a3d81b9ac1f38fc13333d1
```
> have you pulled tags?

Does a fresh `git clone` pull the tags? I also tried with `git fetch --tags` but still get the same output:
```
$ git describe
v0.1.0-462-g9d4b719
$ git describe --tags
v1.1.0-112-g9d4b719
```

**Comment by dominichamon** [comment]
$ git cat-file -t v1.1.0
tag

it's definitely annotated (it would show lightweight otherwise).

Can you 'git pull --tags' and see if it helps?

Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by verbit** [comment]
`git pull --tags` does not help and `git cat-file -t v1.1.0` shows `commit`.

Are you testing this on a fresh `git clone`? Maybe the tag is only annotated in your local repository and not pushed to github?

**Comment by dominichamon** [comment]
I thought of that.. but git push and git push --tags show that everything
is up to date.

and yet...


 $ git clone git@github.com:google/benchmark freshbm
Cloning into 'freshbm'...
remote: Counting objects: 3708, done.
remote: Total 3708 (delta 0), reused 1 (delta 0), pack-reused 3707
Receiving objects: 100% (3708/3708), 976.16 KiB | 0 bytes/s, done.
Resolving deltas: 100% (2441/2441), done.
$ cd freshbm/
$ git tag
v0.0.9
v0.1.0
v1.0.0
v1.1.0
$ git cat-file -t v1.0.0
commit
$ git cat-file -t v1.1.0
commit

o_O

so back to the original checkout and...
$ git push origin v1.0.0
Everything up-to-date
xoanon:~/git/benchmark [master] $ git push origin v1.1.0
To github.com:/google/benchmark
 ! [rejected]        v1.1.0 -> v1.1.0 (already exists)
error: failed to push some refs to 'git@github.com:/google/benchmark'
hint: Updates were rejected because the tag already exists in the remote.

....

$ git pull --tags
From github.com:/google/benchmark
 t [tag update]      v1.1.0     -> v1.1.0
Already up-to-date.
$ git cat-file -t v1.1.0
commit
$ git tag -a -f v1.1.0 v1.1.0
Updated tag 'v1.1.0' (was 4f8bfea)
$ git push --force origin v1.1.0
Counting objects: 1, done.
Writing objects: 100% (1/1), 162 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
To github.com:/google/benchmark
 + 4f8bfea...7ba0caf v1.1.0 -> v1.1.0 (forced update)
$ git cat-file -t v1.1.0
tag


and back to the fresh checkout:

$ git pull --tags
remote: Counting objects: 1, done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.
From github.com:google/benchmark
 t [tag update]      v1.1.0     -> v1.1.0
Already up-to-date.
$ git cat-file -t v1.1.0
tag
$ git cat-file -t v1.0.0
commit


so i'll keep working on v1.0.0, but v1.1.0 should now be annotated.

thanks!


Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by dominichamon** [comment]
v1.0.0 should be annotated correctly too now.



Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by verbit** [comment]
Works now, thanks
