### ISSUE TITLE
static member variable initialized in constructor of benchmark fixture

### ISSUE THREAD

**Issue by spinosae** [google/benchmark#497]
When using a custom class in constructor of a benchmark fixture, I noticed its static member variable was not properly defined.

Upon examination of benchmark.h, I realized the constructor was called in macro REGISTER_BENCHMARK_F. It is called before main function and creates static benchmark objects. According to answers on stack-overflow, initialization of static member variable before first line of main function is implementation dependent. So problem I had can be explained.

Meanwhile the static member variable is correctly defined within main function. Is it possible to register benchmarks in main function? I think it applies to google test too.

Here is a minimal example. Basically I am using a static member variable to store hash code of the class. 
```
#include <iostream>
#include <benchmark/benchmark.h>
#include <typeinfo>
using namespace std;

// helper hashing class
template <class T>
class Hashed {
 public:
  static const size_t Hash;
};

template <class T>
const size_t Hashed<T>::Hash = typeid(T).hash_code();

class Tmp1 : public Hashed<Tmp1> {};

// access static member value
template <class T>
void PrintT() {
  cout << "class: " << typeid(T).name() << " hash: " << T::Hash << endl;
}

class A : public benchmark::Fixture {
 public:
  static const int var1;
  A() { PrintT<Tmp1>(); } // prints 0
};

BENCHMARK_F(A, JustToCallConstructor)
(benchmark::State& st) {}

int main() {
  PrintT<Tmp1>(); // prints correctly
  return 0;
}
```
output of above program
```
class: 4Tmp1 hash: 0
class: 4Tmp1 hash: 776362582
```

**Comment by EricWF** [comment]
I'm not really sure what to do with this. 

Obviously, you've correctly identified this as an classic example of the static initialization order fiasco.

>  Is it possible to register benchmarks in main function?

Yes. https://github.com/google/benchmark#using-registerbenchmarkname-fn-args

**Comment by spinosae** [comment]
Hi @EricWF, thanks for your prompt reply. I am a new user of Google Benchmark. Therefore it took me a while to notice the problem and figure out where the trap was. It is not so obvious that initialization of fixtures happens before main. Wouldn't it be better if benchmarks are registered in main function by default (i.e. in BENCHMARK_MAIN)? 

`RegisterBenchmark` doesn't seem to support fixture benchmark, unless I missed something.

Anyway, this is probably not a common problem. Feel free to close it if you feel it's not relevant.

**Comment by EricWF** [comment]
Yeah, the real bug here is that the library API *just begs* new users to write this kind of bug; and that's on us.

However I'm not exactly sure how to fix it. The current interface to register benchmarks at startup is both widely used and very useful (except when it leads to bugs like this). I don't think we can simply remove it, and there is no simple way to change it so bugs like yours don't occur.

>  Wouldn't it be better if benchmarks are registered in main function by default (i.e. in BENCHMARK_MAIN)?

If by "registered by default" you mean like they currently are now, using the `BENCHMARK` macros, then there is no way to change that interface so that it registers the benchmarks in "main" and not during static initialization.

The real fix is to provide an API which doesn't require static initialization, which is the intent of `RegisterBenchmark`. However, as you point out there is no easy way to use this with fixtures. I'll look into how that can be improved over the semester break. However, with a little creativity it should be simple to transform your fixtures into C++11 lamba's using `RegisterBenchmark`. A somewhat literal translation might look like this (but there are certainly different, if not better ways to de-duplicated the setup/teardown code using lambdas and `RegisterBenchmark`

```c++
// C++11
using benchmark::State;
struct MyFixture {
    void Setup();
    void TearDown();
    // ... Start Test Cases ... //
    void BenchOne(State& st) const;
    void BenchTwo(State& st) const;
    // ... More Benchmarks ... ///

    using BenchmarkCaseT = void(MyFixture::*)(State&) const;
    static void RunCase(State& st, BenchmarkCaseT Case) {
      MyFixture Fixture;
      Fixture.Setup();
      (Fixture.*Case)(st); // Weird C++ member function pointer invocation syntax.
      // In C++17 use std::invoke(Case, Fixture, st);
      Fixture.TearDown();
    }
    static void CreateBenchmarks() {
      using benchmark::RegisterBenchmark;
      auto RunFn = &MyFixture::RunCase;
      RegisterBenchmark("bench1", RunFn, &MyFixture::BenchOne);
      RegisterBenchmark("bench2", RunFn, &MyFixture::BenchTwo);
    }
};

int main(int argc, char** argv) {
  benchmark::Initialize(&argc, argv);
  MyFixture::CreateBenchmarks();
  benchmark::RunSpecifiedBenchmarks();
}
```

As for this particular bug, I'm going to close it and replace it with a meta-bug about how our API causes users to write static initialization order bugs.

Feel free to follow up with any additional questions.

**Comment by EricWF** [comment]
See issue #498.
