### ISSUE TITLE
Suggest clang++

### ISSUE THREAD

**Issue by mstankus** [google/benchmark#502]
When building my first benchmark file, I tried g++ version 7. This did not work.  clang++ did work.  I think that a comment suggesting using clang++ might be helpful. Or at least to help someone determine the choice of compiler for those who are not used to cmake.

Thanks

**Comment by EricWF** [comment]
We support GCC 7. If it isn't working we should fix it (assuming it's our bug), not suggest Clang.
What was the error message you were getting with GCC 7?

Also, I don't think it's the libraries place to suggest what compiler you use. Additionally, I don't see why Clang should be prefered (Just because you ran into problems with GCC?)

**Comment by mstankus** [comment]
You are right. I made an assumption that I should not have. Here is the command which worked in the end. I am on a MAC, I used home-brew to install gcc and it was necessary to include the -lc++ part. 

g++-7   junk.cpp -L /usr/local/lib -I /usr/local/include -lbenchmark -lc++

Should something like "add the -lc++" be added to the documentation
as appropriate?

Mark Stankus

**Comment by EricWF** [comment]
@mstankus Using libc++ with GCC isn't a common use case, including on OS X. (I'm the libc++ maintainer as well, so I can speak to that).

However, since I've needed to do similar things, Google Benchmark has a CMake option to make this use case easier. The option `-DBENCHMARK_USE_LIBCXX=ON` can be used to correctly add the required libc++ flags automatically.

However I don't think we should add the documentation you suggest. First, it's a pretty rare use case, and documenting it may confuse users looking for solutions to other problems. Second, it's still not clear to me *why* we would suggest using libc++ in general. Using GCC on OS X isn't really
a supported configuration for any project. I'm sure you have your reasons, but it's not clear we should document it as a part of this project.

Closing this bug for the above reasons. Please re-open if you disagree or would like to further the discussion.
