### ISSUE TITLE
What is the critera/timing for creating a new release?

### ISSUE THREAD

**Issue by winksaville** [google/benchmark#549]
I recently update ponylang to an arbitrary commit on master as they were at pre v1.1.0. I'd like to update ponylang to a formal release if one might be coming soonish, hence my question.

**Comment by dominichamon** [comment]
Hi Wink

We haven't set up a regular cadence yet. What generally happens is we look
at the list of commits since the last release and if significant things
have landed we tag it. Right now, the key commits since v1.3.0 are:

1. bazel support (non-user-facing)
2. s390x, fuschia, netBSD, Solaris support
3. googletest support (non-user-facing)
4. LTO for Clang
5. better string function compatibility
6. minor fixes and documentation

It may be this is enough for a minor release, but i would like to get in a
couple of the open PRs (#517 or #548, maybe #530).

Is there something specific you're waiting for from this list?


Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by winksaville** [comment]
I submitted 3 PR's in the "minor fixes and documentation" category from pony and I'd like to have an official release sooner rather than later, which is why I asked. If they went in next week and then a release that would be perfect.

So do you think a release next week is possible?

**Comment by dominichamon** [comment]
I'll see if i can get something out this week or early next.

Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by winksaville** [comment]
Thanks

**Comment by rzuckerm** [comment]
I'm also interested in this as well. I would like to start using an official release. I'm currently using the code that is based on the 68e2289 commit that fixed my issue #538

**Comment by dominichamon** [comment]
v1.4.0 is now available: https://github.com/google/benchmark/releases/tag/v1.4.0

**Comment by winksaville** [comment]
@dominichamon THANKS!!!
