### ISSUE TITLE
Cant CMake on Windows with BENCHMARK_ENABLE_ASSEMBLY_TESTS flag

### ISSUE THREAD

**Issue by NTimmons** [google/benchmark#570]
When you use CMake (3.10.2) on Windows 10 with BENCHMARK_ENABLE_ASSEMBLY_TESTS flag enabled it fails to make. 
An [old issue](https://github.com/google/benchmark/issues/564) had the same problem  on Linux but was solved by enabling BENCHMARK_DOWNLOAD_DEPENDENCIES. However, this does not solve the issue on Windows.

It gives this error:
```
CMake Error at test/CMakeLists.txt:175 (message):
  LLVM FileCheck is required when including this file
```

From this section of test/CMakeLists.txt:
```
if (BENCHMARK_ENABLE_ASSEMBLY_TESTS)
  if (NOT LLVM_FILECHECK_EXE)
    message(FATAL_ERROR "LLVM FileCheck is required when including this file")
  endif()
  include(AssemblyTests.cmake)
  add_filecheck_test(donotoptimize_assembly_test)
  add_filecheck_test(state_assembly_test)
  add_filecheck_test(clobber_memory_assembly_test)
endif()
```
For now, I am able to build without the BENCHMARK_ENABLE_ASSEMBLY_TESTS.

**Comment by dominichamon** [comment]
I think this is expected if you don't have LLVM FileCheck available... @EricWF

**Comment by NTimmons** [comment]
That's fine - but the dependency fetcher works on Linux and not Windows?
Shouldn't the behaviour across OS be the same where it is possible? (And if not, documented?)

**Comment by EricWF** [comment]
There is no dependency fetcher for LLVM Filecheck. The bots do some magic, but it's not a part of the supported build.

Even if you did get the dependencies, the tests still wouldn't compile or pass, since the logic that builds them expects a certain assembly syntax and compiler options.

Simply put these tests aren't meant to be built on Windows, at least for now.
