### ISSUE TITLE
Document or discuss group help

### ISSUE THREAD

**Issue by zhihuiFan** [google/benchmark#602]
Hi: 
  the only document I can find is the README.md in this repo.  I checked google-group,  IRC channels, looks all of them are inactive.  Finally I raise [my question](https://stackoverflow.com/questions/50425896/google-benchmark-code-setup) on stackoverflow,  but still few people answered. 

  do we have more documents for this tool or some better places to ask questions? 

Thanks

**Comment by dominichamon** [comment]
The google group <https://groups.google.com/forum/#!forum/benchmark-discuss>
doesn't seem to have any posts since Apr 6th, but it generally gets good
responses.

the IRC channel googlebenchmark on freenode is generally good for
questions, but it may be that our timezones don't overlap. Please do feel
free to use this channel, or groups, or IRC and someone will see it
eventually :)



Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by zhihuiFan** [comment]
Thanks for your quick response!  Due to the timezone,  I will use google group for future questions. Thank you!
