### ISSUE TITLE
docs addition: windows, the missing link

### ISSUE THREAD

**Issue by degski** [google/benchmark#634]
On windows, one needs to link, in addition to benchmark.lib, to Shlwapi.lib. It would be good to include that in the documentation-page, as it would avoid that others also waste an hour or 2, figuring that out.

**Comment by dominichamon** [comment]
This is already done in both the BUILD.bazel and src/CMakeLists.txt files,
and it's documented
https://github.com/google/benchmark/blob/847c0069021ade355b7678a305f3ac4e4d6f7e79/README.md#windows-with-cmake
under known issues.

Is there anywhere else we should add it?

Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by degski** [comment]
@dominichamon 

On the READ.me page it says:

> Don't forget to inform your linker to add benchmark library e.g. through -lbenchmark compilation flag. Alternatively, you may leave out the BENCHMARK_MAIN(); at the end of the source file and link against -lbenchmark_main to get the same default behavior.

there somewhere, I would say, doing that does not work (on it's own) and with vcpkg, that bit is automatic anyway, the linking to that library is not though.

**Comment by dominichamon** [comment]
If you can find a clean way to introduce that to that part of the
documentation (and remove it from the known issues part) then i'd happily
take a look at the PR.

Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by degski** [comment]
@dominichamon 

If you would like to put in the effort (it's actually easier and fool-proof), you could add to benchmark.h

    #ifdef _WIN32
    #pragma comment ( lib, "Shlwapi.lib" )
    #endif 

and nobody would even need to be aware of that requirement.

**Comment by LebedevRI** [comment]
That is only a problem when cmake/cmake-generated install files are *not* used for linking, right?

**Comment by degski** [comment]
Or


    #ifdef _WIN32
    #pragma comment ( lib, "Shlwapi.lib" )
    #ifdef _DEBUG
    #pragma comment ( lib, "benchmarkd.lib" )
    #pragma comment ( lib, "benchmark_maind.lib" )
    #else 
    #pragma comment ( lib, "benchmark.lib" )
    #pragma comment ( lib, "benchmark_main.lib" )
    #endif
    #endif 

It `auto-linking` (this is an old feature, so no worries about backward compatibility), handy (it's not all bad on windows).

**Comment by degski** [comment]
@LebedevRI 
@dominichamon 

It is, because `Shlwapi.lib` library does not get linked automatically, ever. The headers are not in `Windows.h` either, the header is pulled in by `../src/sysinfo.cc`, which hides the fact that the linking is actually required, you won't be any the wiser until  such time you are going to link to benchmark.lib.

**Comment by sharpe5** [comment]
Ye gods, this is just crazy.

Three days trying to get this compiling, and it turns out that it is broken out of the box, and one has to add `shlwapi.lib` as a library. It's even broken in `vcpkg`, nothing works.

Admittedly, this is documented on the front page, but it's a sentence hidden right at the bottom.

So rather than complain, I should open a pull request to improve the docs.

**Comment by ujos** [comment]
I agree with @degski on https://github.com/google/benchmark/issues/634#issuecomment-404166787

In order to create benchmark quickly without going crazy into cmake and vcpkg, as a Windows user I want to create new solution in the Visual Studio, provide path to the include/lib folder and use this nice API. 

I do not want to read documentation, unless it is really required. I do not want to care about what library should I link into my app. Just guide me.

Just a disclaimer. I'm not dummy. I'm just lazy in good meaning of this word. I managed to build BM library and my app in 5 minutes.
