### ISSUE TITLE
 Benchmark should release a new version

### ISSUE THREAD

**Issue by marehr** [google/benchmark#765]
We are >80 commits and a couple of features ahead of the last released version, a new release would be much appreciated.

#310, #419

**Comment by LebedevRI** [comment]
Please don't do that just yet.
I have a lurking suspicion that counter summation from google benchmark threads broke.

**Comment by bryan-lunt** [comment]
@dominichamon I'd really like there to be some kind of release, even a super-minor version, so that I can build my grading infrastructure from an officially hosted release. I want to use the new OpenMP compatibility and rework all of my programming assignments before I hand off all the infrastructure I7ve built to future teachers. However, I don't want to leave the scripts that build VMs pointed at just getting the "master" branch of Benchmark. That could result in incompatibilities further down the road.

Is it possible to have some sort of release? Thanks.

**Comment by dominichamon** [comment]
Yes. I have a label "next-release" to track the PRs to land before doing the next bump. There's currently one open issue: https://github.com/google/benchmark/labels/next-release

**Comment by dominichamon** [comment]
https://github.com/google/benchmark/releases/tag/v1.5

Done.
