### ISSUE TITLE
Does not detect google test?

### ISSUE THREAD

**Issue by emmenlau** [google/benchmark#916]
I've been using Google benchmark 1.4.1 with Google test 1.8.1 successfully on multiple platforms. I build and install Google test, then build Google benchmark against the installed test.

Since switching to benchmark 1.5.0, this does not work anymore. I get an error that Google test is not found. Here is an excerpt from a build on Ubuntu 18.04 x86_64 with cmake 3.16.0. How can I help to debug this issue?

```
-- Looking for Google Test sources
-- Looking for Google Test sources in /data/Debug/googlebenchmark-release-1.5.0/googletest
CMake Error at CMakeLists.txt:34 (message):
  Did not find Google Test sources! Either pass correct path in
  GOOGLETEST_PATH, or enable ALLOW_DOWNLOADING_GOOGLETEST, or disable
  BENCHMARK_ENABLE_GTEST_TESTS / BENCHMARK_ENABLE_TESTING.

CMake Error at /data/Tools/share/cmake-3.16/Modules/ExternalProject.cmake:1783 (get_property):
  get_property could not find TARGET googletest.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  CMakeLists.txt:54 (ExternalProject_Get_Property)


CMake Error at /data/Tools/share/cmake-3.16/Modules/ExternalProject.cmake:1785 (message):
  External project "googletest" has no SOURCE_DIR
Call Stack (most recent call first):
  CMakeLists.txt:54 (ExternalProject_Get_Property)


-- Configuring incomplete, errors occurred!
See also "/data/Debug/googlebenchmark-release-1.5.0-x86_64/third_party/googletest/CMakeFiles/CMakeOutput.log".
CMake Error at cmake/GoogleTest.cmake:13 (message):
  CMake step for googletest failed: 1
Call Stack (most recent call first):
  CMakeLists.txt:273 (include)

-- Configuring incomplete, errors occurred!
```

**Comment by keith-bennett-gbg** [comment]
I am using Googletest separately from Benchmark. I've found that Benchmark does not find a system-installed Googletest nor does it find a user-installed Googletest. To be clear, I am invoking similar to the following:

```bash
$ cd ~/src
$ [ -d googletest ] || git clone "https://github.com/google/googletest"
$ cd googletest
$ mkdir -p build
$ cd build
$ rm -Rf "$(pwd)/*" # clean up any previous build data
$ cmake \
    -DCMAKE_BUILD_TYPE='Release' \
    -DCMAKE_INSTALL_PREFIX="${HOME}" \
    ../ \
  && make -j$(nproc) \
  && ctest -j$(nproc) \
  && make install
```
Googletest is now installed to my `${HOME}`. A different project using CMake can find Googletest using `include(FindGTest)` when I invoke `cmake -DCMAKE_INSTALL_PREFIX="${HOME}"` or `cmake -DCMAKE_PREFIX_PATH="${HOME}"`.

Then, I proceed to do the same with Benchmark:
```bash
$ cd ~/src
$ [ -d benchmark ] || git clone "https://github.com/google/benchmark"
$ cd benchmark
$ mkdir -p build
$ cd build
$ rm -Rf "$(pwd)/*" # clean up any previous build data
$ cmake \
    -DCMAKE_BUILD_TYPE='Release' \
    -DCMAKE_INSTALL_PREFIX="${HOME}" \
    ../ \
  && make -j$(nproc) \
  && ctest -j$(nproc) \
  && make install
```

I would expect that `CMAKE_INSTALL_PREFIX` should be enough for Benchmark to find GoogleTest (since that's enough for `include(FindGTest)` to work). However that is not the case. The error message that is displayed says:
```
-- Looking for Google Test sources
-- Looking for Google Test sources in /home/keithb/dev/benchmark/googletest
CMake Error at CMakeLists.txt:34 (message):
  Did not find Google Test sources! Either pass correct path in
  GOOGLETEST_PATH, or enable ALLOW_DOWNLOADING_GOOGLETEST, or disable
  BENCHMARK_ENABLE_GTEST_TESTS / BENCHMARK_ENABLE_TESTING.
```

I don't really care if it Benchmark downloads its own copy of Googletest or if it uses the one I've installed -- I don't have dependency-hell at this stage and I just needed to get something working. However, the error message is incorrect: adding `-DALLOW_DOWNLOADING_GOOGLETEST=ON` does not resolve the problem. Instead, it looks like `-DBENCHMARK_DOWNLOAD_DEPENDENCIES=ON` _did_ solve the problem and allow me to move forward.

**Comment by LebedevRI** [comment]
Note that since https://github.com/google/benchmark/pull/809 the cmake buildsystem no longer looks for binary prebuilt version of googletest, but only for googletest sources.
So you need to either point it at the googletest sources, or tell it to download them.

**Comment by emmenlau** [comment]
Could it be re-added that an external googletest can be used (linked) as is, or is there a strong reason why benchmark needs its own internal copy?

**Comment by LebedevRI** [comment]
Note that it doesn't need *internal* copy, it only needs the sources,
the location of which you can pass via `-DGOOGLETEST_PATH=/x/y/z`

**Comment by emmenlau** [comment]
Dear Roman, thanks for your help but I'm not sure I understand. What does it do with the sources, if not compile and link? Do the sources need to match the version of googletest that is later linked against?

**Comment by emmenlau** [comment]
Dear @LebedevRI I'm still not able to use google benchmark due to this issue. Could you motivate again why google benchmark requires sources of google test?

**Comment by LebedevRI** [comment]
> I've read #809 and I'm under the impression what you say here is not correct:
> 
> > Note that it doesn't need _internal_ copy, it only needs the sources,
> > the location of which you can pass via `-DGOOGLETEST_PATH=/x/y/z`

I'm confused. Why are you under the impression that what i said in that quote is not correct?

> I think it _does_ compile the sources and use it as a binary version of google test.

^ that is precisely what i meant. Why _else_ would the sources be needed?

> This is contrary to what I want. Please make it possible again to have a single version of google test that is used.

See https://github.com/google/benchmark/pull/809#issuecomment-487903930 from the PR you linked.

> Please avoid that google benchmark ships a separate copy of google test.

Define ships?
Can you please show where google benchmark ships a separate copy of google test?

> Currently when linking google test and google benchmark into the same executable, the used google test is undefined (dependent on link order).

Please can you show where google benchmark library (that you link to) itself links to google test?

**Comment by emmenlau** [comment]
Dear @LebedevRI , I think you are trying to be unhelpful, and I do not understand why.

You say that google benchmark *requires* the sources of google test. But then you deny it includes its own internal copy of the binaries, nor would it link to google test, nor would it ship google test. This is *obviously* counter-intuitive. And I've asked already before if you can help solve this mystery. Yet you remain completely ignorant to this question. Instead ask *me* as to where google test is included in google benchmark. I must conclude that you are trying to prove a point instead of being helpful. But I fail to understand what that point may be.

After two months, can you, or can you not, help understand why google benchmark requires sources of google test, and if that has implications on users linking *their own*, possibly patched copy of google test?

**Comment by dominichamon** [comment]
Allow me to cleave this gordian known in twain.

when building the tree from source in a clean pull from github, it will use googletest. this is because the googletest flag is enabled for benchmark developers.

if all you want is the _library_ to link against, then you can disable tests and build the library _without_ googletest.

benchmark requires googletest sources so we can test it. benchmark does not require googletest sources if you only want to use it.

**Comment by emmenlau** [comment]
Ahahahaha! Ok!
Thank you so much @dominichamon , then I will be able to use benchmark 1.5!

**Comment by LebedevRI** [comment]
I think we are hitting a terminology barrier here.
