### ISSUE TITLE
Provide benchmark:: Aliased CMake Library

### ISSUE THREAD

**Issue by jwillikers** [google/benchmark#921]
It's common to provide an aliased version of libraries that include the import prefix to make switching between ```find_package``` and ```add_subdirectory``` calls effortless. Because the ```benchmark::benchmark``` and ```benchmark::benchmark_main``` targets do not have aliased targets, users must switch between ```benchmark::benchmark``` and ```benchmark``` in ```target_link_libraries```.
Adding an aliased library with CMake is as easy as:
```cmake
add_library(benchmark::benchmark ALIAS benchmark)
```

**Comment by keith-bennett-gbg** [comment]
Note this was also relevant to me when building something depending on benchmark using `find_package` with a system installed benchmark (`cmake && sudo make install`) and then migrating to a user-installed (`cmake -DCMAKE_INSTALL_PREFIX=${HOME} && make install`). Turns out the project depending on benchmark was linking to `benchmark` and was finding the system installed benchmark but would break when building the user installed benchmark (`fatal error: benchmark/benchmark.h: No such file or directory`). Using `benchmark::benchmark` fixed the user installed benchmark and the system installed package consistently worked too.

That makes sense and the bug was obviously on my end. Remember, cmake links against `benchmark` alone if it can't find the target, and the compiler found the system-installed library. CMake did _not_ add any include directories because the correct target was _not_ used, but because benchmark was system installed, the compiler found the system-installed headers too. Migrating to a user install meant that the compiler couldn't pick up the slack and showed that CMake wasn't telling me that I'm not correctly using the benchmark target. I _really_ wish CMake could tell and warn or error when that happens.

I think it would be nice if there's a few different examples and includes `benchmark::benchmark` with `find_package(benchmark REQUIRED)` instead of leaving me to (incorrectly) guess as it is currently. I'd considered using `add_subdirectory` instead to work around the problem but found this issue while searching for any known issues with installing benchmark. It gave me the insight to try using `target_link_libraries(mytarget benchmark::benchmark)` which solved the problem: cmake now recognized the target and automatically added the necessary include directory to `mytarget`.

Specifically: the README includes [Installation](https://github.com/google/benchmark/blob/5ce2429af7a8481581896afaa480552cc7584808/README.md#installation) with some example of installing benchmark with cmake. It also includes [Usage](https://github.com/google/benchmark/blob/5ce2429af7a8481581896afaa480552cc7584808/README.md#usage) showing how to use Benchmark in C++ code. I think an improvement could be made here to demonstrate using benchmark in cmake, showing an example of `find_package` and `add_subdirectory`.

**Comment by LebedevRI** [comment]
SGTM, feel free to submit a pull request.

**Comment by jwillikers** [comment]
@LebedevRI @keith-bennett-gbg I am working on a pull request now 👍
