### ISSUE TITLE
can not configure the solution with ninja clang 10 (windows 10)

### ISSUE THREAD

**Issue by GaussGreen** [google/benchmark#974]
when compiling project from GitHub with google benchmark using cmake, ninja and clang 10( clang++) in windows 10. the configuration fails with the following issues.
-- Performing Test HAVE_THREAD_SAFETY_ATTRIBUTES
-- Performing Test HAVE_THREAD_SAFETY_ATTRIBUTES -- failed to compile
-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX -- failed to compile
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX -- failed to compile
CMake Error at deps/googlebenchmark/CMakeLists.txt:183 (message):
  Failed to determine the source files for the regular expression backend

**Comment by dominichamon** [comment]
i don't have a windows 10 machine on which to test this out. i'm hoping someone out there does.

in the mean time, can you share the more verbose cmake logs generated so we can see what it tried to compile and what failed?

**Comment by LebedevRI** [comment]
Is that when doing cross-compilation?

**Comment by jeremyong** [comment]
I can confirm this is an issue. This is not when doing cross-compilation but just using the native windows version of the Clang compiler. A small test project with the same regex test file compiles perfectly fine with `target_cxx_features(test PUBLIC cxx_std_17)` and if I just invoke `set(HAVE_STD_REGEX ON)` prior to adding the benchmark subdirectory, things work. As it is, the cxx feature test appears broken.

**Comment by jeremyong** [comment]
I see the issue, if in `CXXFeatureCheck.cmake`, you pass `-DCMAKE_CXX_STANDARD=14` or `-DCMAKE_CXX_STANDARD=17` to `try_run(RUN_${FEATURE}...`, the test compilation succeeds. It appears that Windows Clang has a regex bug for C++11 which is the default standard set when `try_run` is invoked. I suggest upping the standard to something a bit more recent, since the benchmark library can internally set what C++ standard it wants to build against. This setting could also be set specifically for this OS/Compiler tuple. Is there interest in a PR?

**Comment by dominichamon** [comment]
Thanks for tracking that down, @jeremyong!

I would be interested in a PR. Given we allow the library to be built with modern C++ (though we require the _header_ to support older compilers), upping to post C++11 works for me.

**Comment by jeremyong** [comment]
Done! Let me know if you need any other changes or feel free to change it yourself.
